name: Rust

on:
  push:
    branches: [develop, main, "release/**", "feature/**", "patch/**"]
  pull_request:
    branches: [develop, main, "release/**", "feature/**", "patch/**"]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
